In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("text_emotion.csv")

In [4]:
data.head()

tweet_id   sentiment       author  \
0  1956967341       empty   xoshayzers   
1  1956967666     sadness    wannamama   
2  1956967696     sadness    coolfunky   
3  1956967789  enthusiasm  czareaquino   
4  1956968416     neutral    xkilljoyx   

                                             content  
0  @tiffanylue i know  i was listenin to bad habi...  
1  Layin n bed with a headache  ughhhh...waitin o...  
2                Funeral ceremony...gloomy friday...  
3               wants to hang out with friends SOON!  
4  @dannycastillo We want to trade with someone w...

In [5]:
data = data.drop('author',axis=1)

In [6]:
data.head(10)

tweet_id   sentiment                                            content
0  1956967341       empty  @tiffanylue i know  i was listenin to bad habi...
1  1956967666     sadness  Layin n bed with a headache  ughhhh...waitin o...
2  1956967696     sadness                Funeral ceremony...gloomy friday...
3  1956967789  enthusiasm               wants to hang out with friends SOON!
4  1956968416     neutral  @dannycastillo We want to trade with someone w...
5  1956968477       worry  Re-pinging @ghostridah14: why didn't you go to...
6  1956968487     sadness  I should be sleep, but im not! thinking about ...
7  1956968636       worry               Hmmm. http://www.djhero.com/ is down
8  1956969035     sadness            @charviray Charlene my love. I miss you
9  1956969172     sadness         @kelcouch I'm sorry  at least it's Friday?

In [7]:
data['sentiment'].unique()

array(['empty', 'sadness', 'enthusiasm', 'neutral', 'worry', 'surprise',
       'love', 'fun', 'hate', 'happiness', 'boredom', 'relief', 'anger'],
      dtype=object)

In [8]:
data.head(10)

tweet_id   sentiment                                            content
0  1956967341       empty  @tiffanylue i know  i was listenin to bad habi...
1  1956967666     sadness  Layin n bed with a headache  ughhhh...waitin o...
2  1956967696     sadness                Funeral ceremony...gloomy friday...
3  1956967789  enthusiasm               wants to hang out with friends SOON!
4  1956968416     neutral  @dannycastillo We want to trade with someone w...
5  1956968477       worry  Re-pinging @ghostridah14: why didn't you go to...
6  1956968487     sadness  I should be sleep, but im not! thinking about ...
7  1956968636       worry               Hmmm. http://www.djhero.com/ is down
8  1956969035     sadness            @charviray Charlene my love. I miss you
9  1956969172     sadness         @kelcouch I'm sorry  at least it's Friday?

In [9]:
data['content'] = data['content'].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [10]:
data['content'] = data['content'].str.replace('[^\w\s]',' ')

In [11]:
data.head()

tweet_id   sentiment                                            content
0  1956967341       empty   tiffanylue i know i was listenin to bad habit...
1  1956967666     sadness  layin n bed with a headache ughhhh   waitin on...
2  1956967696     sadness                funeral ceremony   gloomy friday   
3  1956967789  enthusiasm               wants to hang out with friends soon 
4  1956968416     neutral   dannycastillo we want to trade with someone w...

In [12]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
data['content'] = data['content'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

In [13]:
from nltk.stem import WordNetLemmatizer
l = WordNetLemmatizer()
data['content'] = data['content'].apply(lambda x: " ".join([l.lemmatize(word) for word in x.split()]))

In [14]:
data['content'].head()

0    tiffanylue know listenin bad habit earlier sta...
1              layin n bed headache ughhhh waitin call
2                       funeral ceremony gloomy friday
3                                want hang friend soon
4    dannycastillo want trade someone houston ticke...
Name: content, dtype: object

In [15]:
import re
def de_repeat(text):
    pattern = re.compile(r"(.)\1{2,}")
    return pattern.sub(r"\1\1", text)

In [16]:
data['content'] = data['content'].apply(lambda x: " ".join(de_repeat(x) for x in x.split()))

In [17]:
freq = pd.Series(' '.join(data['content']).split()).value_counts()[-10000:]

In [18]:
freq = list(freq.index)
data['content'] = data['content'].apply(lambda x: " ".join(x for x in x.split() if x not in freq))

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
from sklearn import preprocessing
lbl_enc = preprocessing.LabelEncoder()
y = lbl_enc.fit_transform(data.sentiment.values)

In [21]:
list(lbl_enc.inverse_transform([0,1,2,3,4,5,6,7,8,9,10,11,12]))

C:\Users\Chaitu\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


['anger',
 'boredom',
 'empty',
 'enthusiasm',
 'fun',
 'happiness',
 'hate',
 'love',
 'neutral',
 'relief',
 'sadness',
 'surprise',
 'worry']

In [22]:
x_train,x_test,y_train,y_test = train_test_split(data.content.values,y)

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
vec = CountVectorizer(min_df=5,ngram_range=(1,5)).fit(x_train)

In [25]:
vec.get_feature_names()

['00',
 '05',
 '06',
 '08',
 '09',
 '10',
 '10 30',
 '10 day',
 '10 min',
 '10 minute',
 '10 year',
 '100',
 '100th',
 '10am',
 '10pm',
 '10th',
 '11',
 '11 11',
 '12',
 '12 hour',
 '12th',
 '13',
 '14',
 '14 hour',
 '140',
 '140 character',
 '15',
 '15 min',
 '15 minute',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1am',
 '1st',
 '1st time',
 '20',
 '200',
 '2008',
 '2009',
 '2010',
 '21',
 '22',
 '23',
 '24',
 '24 hour',
 '24 hr',
 '25',
 '26',
 '27',
 '28',
 '29',
 '2am',
 '2b',
 '2day',
 '2moro',
 '2morrow',
 '2nd',
 '2night',
 '2nite',
 '2pm',
 '2uhs',
 '30',
 '30 min',
 '30 minute',
 '300',
 '30am',
 '30pm',
 '31',
 '32',
 '33',
 '35',
 '360',
 '38',
 '3am',
 '3d',
 '3d movie',
 '3rd',
 '40',
 '400',
 '45',
 '45am',
 '48',
 '4am',
 '4pm',
 '4th',
 '4th happy',
 '4th happy star',
 '4th happy star war',
 '4th happy star war day',
 '4th quot',
 '50',
 '500',
 '5am',
 '5k',
 '5pm',
 '5th',
 '60',
 '6am',
 '6pm',
 '6th',
 '70',
 '75',
 '7am',
 '7pm',
 '7th',
 '80',
 '8am',
 '8th',
 '90',
 

In [26]:
vecv = vec.transform(x_train)

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
model = LogisticRegression()

In [29]:
model.fit(vecv,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [30]:
fnames  = np.array(vec.get_feature_names())

In [31]:
mc = model.coef_[0].argsort()

In [32]:
fnames[mc[:10]]

array(['see', 'still', 'miss', 'thanks', 'oh', 'night', 'today',
       'twitter', 'morning', 'happy'], dtype='<U43')

In [33]:
fnames[mc[-11:-1]]

array(['bout', 'hard', 'link', 'left', 'seriously', 'mummy', 'sister',
       'fucking', 'gah', 'taste'], dtype='<U43')

In [34]:
model.predict(vec.transform(["He is good"]))

array([8], dtype=int64)

In [35]:
x_val = vec.transform(x_test)

In [36]:
y_pred = model.predict(x_val)

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_pred,y_test)

0.3362

In [39]:
from sklearn.ensemble import RandomForestClassifier

C:\Users\Chaitu\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [40]:
rc = RandomForestClassifier()

In [41]:
rc.fit(vecv,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [42]:
pre  = rc.predict(x_val)

In [43]:
accuracy_score(pre,y_test)

0.2854

In [44]:
from sklearn.naive_bayes import MultinomialNB
mb = MultinomialNB()

In [45]:
mb.fit(vecv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [46]:
p =  mb.predict(x_val)

In [47]:
accuracy_score(p,y_test)

0.3266

In [48]:
zc = mb.coef_[0].argsort()

In [53]:
mb.predict(vec.transform(["Uska is a good girl"]))

array([5], dtype=int64)

In [50]:
from sklearn.metrics import confusion_matrix

In [51]:
confusion_matrix(y_test,y_pred)

array([[   0,    0,    0,    0,    1,    3,    0,    0,    9,    2,    4,
           1,   10],
       [   0,    0,    1,    0,    1,    4,    3,    2,   12,    1,    5,
           1,   20],
       [   0,    1,    0,    1,    0,    9,    3,    6,  121,    0,   15,
           0,   46],
       [   0,    0,    1,    0,    3,   28,    2,   12,   80,    4,   13,
           2,   60],
       [   0,    0,    0,    1,   17,  113,    2,   33,  162,    6,   30,
           8,   82],
       [   0,    0,    0,    3,   33,  415,    5,  161,  404,   24,   49,
          39,  158],
       [   0,    1,    1,    0,    5,   11,   59,    8,   85,    3,   57,
           9,   79],
       [   0,    0,    0,    0,   15,  174,    5,  388,  170,    5,   44,
          11,   81],
       [   0,    1,    1,    1,   25,  199,   13,   78, 1226,   21,  119,
          30,  433],
       [   0,    0,    0,    1,    5,   63,    4,   28,  144,   13,   22,
           4,   63],
       [   0,    0,    5,    0,   14,   66,   40, 